trigger: 
 - none

pool:
   name: 'cicd'

steps: 
- task: GoTool@0
  displayName: GoTool
  inputs:
    version: '1.13.5'
- task: Go@0
  displayName: GoGet
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: GoBuild
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar con'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'webapps'
    cliProjectName: 'webapps'
    cliSources: '.'
- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_21_X64'
- task: CmdLine@2
  displayName: Trivy FS scan
  inputs:
    script: 'trivy fs --format table -o trivy-fs-report.html .'
- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'docker conn'
    repository: 'web'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    addPipelineData: false
    addBaseImageData: false
- task: HelmInstaller@0
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true
- task: HelmDeploy@1
  inputs:
    azureSubscriptionForACR: 'Visual Studio Enterprise Subscription
    azureResourceGroupForACR: 'akstest'
    azureContainerRegistry: 'devops8983.azurecr.io'
    command: 'package'
    chartPath: 'helm/go-web-app-chart'
    chartVersion: '$(Build.BuildId)'
    chartNameForACR: 'web'
    chartPathForACR: 'helm'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: CmdLine@2
  displayName: Trivy Image scan
  inputs:
    script: 'trivy image --format table -o trivy-image-report.html  devops8983.azurecr.io/web:$(Build.BuildId)'
